version: 2

project_name: clickhouse-dash

builds:
  - id: clickhouse-dash
    main: .
    binary: clickhouse-dash
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - public/**/*

checksum:
  name_template: checksums.txt

release:
  github:
    owner: SCcagg5
    name: clickhouse-dash